### ISSUE TITLE
Does this only work for msmbuilder-legacy? I couldnt find Cluster.py in the scripts directory of msmbuilder package which i installed..

### ISSUE THREAD

**Issue by anuginu** [rmcgibbo/GPURMSD#1]

**Comment by rmcgibbo** [comment]
Yes, this code is not maintained anymore and is not compatible with the latest releases of msmbuilder

**Comment by anuginu** [comment]
Thank you for the reply.Is there a way to run multiple msm building
processes(tics, clustering etc) in GPU?
Thanks
Anu

**Comment by rmcgibbo** [comment]
No, I don't believe that the whole pipeline has been implemented on GPUs in any version of the msmbuilder software.
